version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mongodb://mongodb:27017/nest
    depends_on:
      - mongodb
      - redis
    networks:
      - local

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - local

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - local

networks:
  local:
    driver: bridge
